version: 2.1
orbs:
  docker: circleci/docker@1.0.0
workflows:
  test-build-deploy:
    jobs:
      - test-calc:
          context:
            - docker-hub-creds
      - build-and-test-python-sdk

jobs:
  test-calc:
    docker:
      - image: equaltodev/rust:1.65.0-2
        auth:
          username: $DOCKER_HUB_ID
          password: $DOCKER_HUB_PASSWORD
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run packages/calc tests
          command: |
            cd packages/calc
            make tests
      - store_artifacts:
          path: ~/repo/packages/calc/target/llvm-cov
  build-and-test-python-sdk:
    docker:
      - image: rust:1.65.0-slim
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt update
            apt -y --no-install-recommends upgrade
            apt install --no-install-recommends -y make python3 pip
            rustup component add rustfmt clippy
      - run:
          name: Build EqualTo python SDK
          command: make venv
          working_directory: ./packages/sdk/python
      - run:
          name: Run linters
          command: make lint
          working_directory: ./packages/sdk/python
      - run:
          name: Run tests
          command: make coverage
          working_directory: ./packages/sdk/python
      - store_artifacts:
          path: ~/repo/packages/sdk/python/tests/htmlcov
