[package]
name = "pycalc"
version = "0.2.0"
authors = ["Nicolás Hatcher <nicolas.hatcher@equalto.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pycalc"
# "cdylib" is necessary to produce a shared library for Python to import from.
# crate-type = ["cdylib", "rlib"]
crate-type = ["cdylib"]
[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
equalto_calc = { path = "../equalto_calc" }
equalto_xlsx = { path = "../equalto_xlsx" }

# See: https://github.com/PyO3/pyo3/issues/340
[dependencies.pyo3]
version = "0.13.2"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]