[package]
name = "equalto_wasm"
version = "0.1.0"
authors = ["EqualTo <dev@equalto.com>"]
edition = "2021"
publish = false

# We run `wasm-opt` externally, because the bundled prebuilt binary isn't available for linux/arm64
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
equalto_calc = { path = "../../calc/equalto_calc" }
equalto_xlsx = { path = "../../calc/equalto_xlsx", optional = true }
gloo-utils = { version = "0.1.5", features = ["serde"] }
js-sys = "0.3.60"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = "0.2.83"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[features]
xlsx = ["equalto_xlsx"]
