version: "3"

services:
  server:
    build:
      context: ..
      dockerfile: ./sheet_ai/server/Dockerfile
      args:
        - GIT_COMMIT=${GIT_COMMIT}
    volumes:
      - ./server/:/server
    env_file: ./server/wsgi/.env
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - database
    networks:
      - backend
  database:
    image: mongo
    restart: always
    volumes:
      - /data/db
    env_file: ./server/wsgi/.env
    ports:
      - '27017:27017'
    networks:
      - backend

networks:
  backend:
    driver: bridge
