[package]
name = "equalto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { version = "0.25"}
ratatui = { version = "0.20", default-features = false, features = ['crossterm'] }
equalto_calc = { path = "../calc/equalto_calc" }
equalto_xlsx = { path = "../calc/equalto_xlsx" }


